### ISSUE TITLE
On Nueral biaprtite matching

### ISSUE THREAD

**Issue by nahondobruno** [HekpoMaH/Neural-Bipartite-Matching#1]
when i run flow_datasets.py file in the Neural bipartite matching, i get this error: i have tried to resolve it but until now i have failed.some assistance pliz. Plus how can support this page in terms of donation, can it accept visa card payment.
File ~/ns-allinone-3.38/ns-3.38/km/flow_datasets.py:209
f = SingleIterationDataset('./all_iter', split='test', less_wired=True, device='cpu', probp=3, probq=4)

TypeError: Can't instantiate abstract class SingleIterationDataset with abstract method len

**Comment by HekpoMaH** [comment]
Dear `balexx2`,

This project is about 4 years old. If you're using the latest versions of NN libraries, such as PyG/PyTorch, quite likely there's an API mismatch. (Which I believe is the case here).

For example, if you take a look at `flow_datasets.py`, there are `__len__` functions defined. You can use these to define `len`, function in the class. E.g.

```
    def len(self):
        return self.__len__()
```

Furthermore, you're not supposed to run `flow_datasets.py`. It's a file that's imported by other scripts. Did you take a look at the README provided and follow the steps, before opening the issue?

Lastly, this is not a webpage/charitable/profitable project so there is no need to donate and support it. Also, as this is a research, not an industry project, I have no plans to update it to use the latest libraries.

**Comment by nahondobruno** [comment]
Thanks so much Prof.

**Comment by nahondobruno** [comment]
Hello Prof, I embarked on understanding **Nueral  bipartite matching** as clearly explained in your paper. i have tested 98% of  your successfully. i have only met the error: **IndexError: index 6 is out of bounds for dimension 0 with size 6** and it points to utils.py script especially at this function:
**def create_inv_edge_index(batch_size, size, edge_index):
    iei = torch.full((batch_size*size, batch_size*size), -100, dtype=torch.long)
    for i in range(len(edge_index[0])):
        iei[edge_index[0][i]][edge_index[1][i]] = i
    return iei**
 tedge_index = torch.tensor(edge_index).clone().detach()
tensor([[ 5.,  1.],
        [ 1.,  1.],
        [14.,  1.],
        [ 7.,  1.],
        [ 1.,  1.],
        [ 6.,  1.],
        [12.,  1.],
        [14.,  1.],
        [15.,  1.],
        [ 5.,  1.],
        [10.,  1.],
        [ 2.,  0.],
        [ 9.,  0.],
        [14.,  0.],
        [15.,  0.],
        [13.,  0.],
        [ 5.,  0.],
        [ 3.,  0.],
        [10.,  0.],
        [ 9.,  0.],
        [15.,  0.],
        [14.,  0.]], grad_fn=<CatBackward0>)
ROOT ./bfs_less_wired
PROCESSED bfs_less_wired/processed
ROOT ./bfs_less_wired
PROCESSED bfs_less_wired/processed
ROOT ./all_iter_less_wired
PRP []
PROCESSED all_iter_less_wired/processed
ROOT ./all_iter_less_wired
PRP []
PROCESSED all_iter_less_wired/processed
Processing...
Done!
Processing...
Done!
Processing...
Done!
Processing...
Done!
Traceback (most recent call last):

  File "/tmp/ipykernel_5044/3463109613.py", line 73, in <module>
    inv_edge_index = utils.create_inv_edge_index(len(GRAPH_SIZES), GRAPH_SIZES.max(), batch.edge_index)

  File "/home/nahondo/Desktop/nsm/utils.py", line 221, in create_inv_edge_index
    iei[edge_index[0][i]][edge_index[1][i]] = i

**IndexError: index 6 is out of bounds for dimension 0 with size 6**
